config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'links#index'
  resources:links, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
	validates :title, presence: true
	validates :url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	def index
		@links = Link.all
	end

	def new
		@link = Link.new
	end

	def create
		@link = Link.new(link_params)
		if @link.save
			redirect_to root_path
		else
			render :new
		end
	end

	private

	def link_params
		params.require(:link).permit(:title, :url)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/index.html.erb
<%= link_to "Submit a new link", new_link_path %>


<table>
	<% @links.each do |link| %>
		<tr id=<%= "link_id_#{link.id}" %>>
			<td><%= link_to link.title, link.url %></td>
			<td><%= link_to 'Upvote' %></td>
			<td data-role='score' ><%= link.score %></td>	
		</tr>
	<% end %>
</table>

app/views/links/new.html.erb
<%= @link.errors.full_messages.first if @link.errors.any? %>
<%= form_for @link do |form| %>
 	<%= form.text_field :title, id: :link_title %>
 	<%= form.text_field :url, id: :link_url %>
 	<%= form.submit 'Submit!' %>
<% end %>